### ISSUE TITLE
Could not open file ./prediction/deploy.prototxt

### ISSUE THREAD

**Issue by Victoria2333** [VisionLearningGroup/Ask_Attend_and_Answer#6]
I changed my caffe path to /home/han/src/caffe in./bashrc,
but when i run prediction_json.py,there is still error:
han@han:~/Ask_Attend_and_Answer-master/example/prediction$ python predict_json.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0929 20:04:09.720854 20851 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0929 20:04:09.720896 20851 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0929 20:04:09.720903 20851 _caffe.cpp:142] Net('./prediction/deploy.prototxt', 1, weights='./prediction/mm_iter_243000.caffemodel')
Traceback (most recent call last):
  File "predict_json.py", line 28, in <module>
    lstmnet = caffe.Net(DEPLOY, MODEL, caffe.TEST)
RuntimeError: Could not open file ./prediction/deploy.prototxt
Could you please give me some advice on it?

**Comment by huijuan88** [comment]
Try to change the folder where you execute the prediction code.

cd ~/Ask_Attend_and_Answer-master/example/
python predict_json.py





On Sep 29, 2017, at 08:09, Victoria2333 <notifications@github.com<mailto:notifications@github.com>> wrote:


I changed my caffe path to /home/han/src/caffe in./bashrc,
but when i run prediction_json.py,there is still error:
han@han:~/Ask_Attend_and_Answer-master/example/prediction$ python predict_json.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0929 20:04:09.720854 20851 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0929 20:04:09.720896 20851 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0929 20:04:09.720903 20851 _caffe.cpp:142] Net('./prediction/deploy.prototxt', 1, weights='./prediction/mm_iter_243000.caffemodel')
Traceback (most recent call last):
File "predict_json.py", line 28, in
lstmnet = caffe.Net<http://caffe.net>(DEPLOY, MODEL, caffe.TEST)
RuntimeError: Could not open file ./prediction/deploy.prototxt
Could you please give me some advice on it?

**Comment by Victoria2333** [comment]
thanks,i just tried just the minute when i got  your reply,and it occurred:
han@han:~/Ask_Attend_and_Answer-master/example$ python ./prediction/predict_json.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0929 21:15:31.683986 21642 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0929 21:15:31.684031 21642 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0929 21:15:31.684039 21642 _caffe.cpp:142] Net('./prediction/deploy.prototxt', 1, weights='./prediction/mm_iter_243000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 2180:18: Message type "caffe.LayerParameter" has no field named "word_sum_param".
F0929 21:15:31.723026 21642 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./prediction/deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
It seems thhere is some error in deploy.prototxt,because i found field named "word_sum_param" in layer params.

**Comment by huijuan88** [comment]
Did you use my provided caffe? It has some new layers integrated, e,g. word_sum_param.




On Sep 29, 2017, at 09:18, Victoria2333 <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks,i just tried just the minute when i got your reply,and it occurred:
han@han:~/Ask_Attend_and_Answer-master/example$ python ./prediction/predict_json.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0929 21:15:31.683986 21642 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0929 21:15:31.684031 21642 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0929 21:15:31.684039 21642 _caffe.cpp:142] Net('./prediction/deploy.prototxt', 1, weights='./prediction/mm_iter_243000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 2180:18: Message type "caffe.LayerParameter" has no field named "word_sum_param".
F0929 21:15:31.723026 21642 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./prediction/deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by Victoria2333** [comment]
Thank you,I changed caffe to yours,and it worked!
But where should i check the test accuracy? I can only see the result json  ...

**Comment by Victoria2333** [comment]
@ huijuan88 ,sorry to bother, I read your paper <<Ask,Attend and Answer>>, I see there are Absolute position experiment in Fig.3 , Relative position experiment in Fig.4 ,Visualization of the spatial attention weights in the SMem-VQA model in Fig.5 and Fig.6 either.
And i couldn't find them in your project,and your test accuracy...
Waiting for your reply~Thank you~~

**Comment by huijuan88** [comment]
Upload the json file to the VQA challenge server, get the evaluation result.

Huijuan


On Sep 30, 2017, at 08:29, Victoria2333 <notifications@github.com<mailto:notifications@github.com>> wrote:


@ huijuan88 ,sorry to bother, I read your paper <<Ask,Attend and Answer>>, I see there are Absolute position experiment in Fig.3 , Relative position experiment in Fig.4 ,Visualization of the spatial attention weights in the SMem-VQA model in Fig.5 and Fig.6 either.
And i couldn't find them in your project,and your test accuracy...
Waiting for your reply~Thank you~~

**Comment by Victoria2333** [comment]
@huijuan88 ,and what about your other experiments??
Thanks for your help~
